### ISSUE TITLE
Question about the reported performence

### ISSUE THREAD

**Issue by Len-Li** [simon3dv/frustum_pointnets_pytorch#1]
Hello, thanks for you great work.I've not read all of your code yet. But I have a question about the reported AP. When using rgb detection, 3d result is 85.09, 72.11, 64.25, while with gt box, 3d result is 68.41, 63.89, 66.46 which fall behind rgb detection. I am confused about it so I am appreciate it if you can talk about these phenomenon.

**Comment by simon3dv** [comment]
Hi @LehengLi , the reason is f-pointnets cannot output a good "**score**", which is important when calculating pascal voc  AP. You can check it in `train/test.py`

When testing with rgb detection, the "score" is from rgb detection, so no problem.

> score_list.append(batch_rgb_prob[j])


When testing with 2d gt, the "score" is cauculated by:(which is from official tensorflow codes)
> mask_mean_prob = np.sum(batch_seg_prob * batch_seg_mask, 1)  # B,
mask_mean_prob = mask_mean_prob / (np.sum(batch_seg_mask, 1))
batch_scores = np.log(mask_mean_prob) + np.log(heading_prob) + np.log(size_prob)
score_list.append(batch_scores[j])

It seems no problem but AP falls. 
If I use the same way `score_list.append(batch_scores[j])` to test with rgb detection,  AP will fall too:  `AP: 76.976532 69.313423 63.041763`

## Solution
The easiest way is to calculate score in this way:
```
mask_max_prob = np.max(batch_seg_prob * batch_seg_mask, 1)
batch_scores = np.max(mask_max_prob)
```
the result will be:
using rgb detection:` car_detection_3d AP: 81.558723 70.068161 63.369583`
using 2d gt:`car_detection_3d AP: 85.082458 74.658356 67.191765`

Besides, train a classification branch like f-convnet would be better.

**Comment by Len-Li** [comment]
> Hi @LehengLi , the reason is f-pointnets cannot output a good "**score**", which is important when calculating pascal voc AP. You can check it in `train/test.py`
> 
> When testing with rgb detection, the "score" is from rgb detection, so no problem.
> 
> > score_list.append(batch_rgb_prob[j])
> 
> When testing with 2d gt, the "score" is cauculated by:(which is from official tensorflow codes)
> 
> > mask_mean_prob = np.sum(batch_seg_prob * batch_seg_mask, 1)  # B,
> > mask_mean_prob = mask_mean_prob / (np.sum(batch_seg_mask, 1))
> > batch_scores = np.log(mask_mean_prob) + np.log(heading_prob) + np.log(size_prob)
> > score_list.append(batch_scores[j])
> 
> It seems no problem but AP falls.
> If I use the same way `score_list.append(batch_scores[j])` to test with rgb detection, AP will fall too: `AP: 76.976532 69.313423 63.041763`
> 
> ## Solution
> The easiest way is to calculate score in this way:
> 
> ```
> mask_max_prob = np.max(batch_seg_prob * batch_seg_mask, 1)
> batch_scores = np.max(mask_max_prob)
> ```
> 
> the result will be:
> using rgb detection:` car_detection_3d AP: 81.558723 70.068161 63.369583`
> using 2d gt:`car_detection_3d AP: 85.082458 74.658356 67.191765`
> 
> Besides, train a classification branch like f-convnet would be better.

simon3dv: Amazing! thanks for your kindly reply.
